### ISSUE TITLE
No set_looping on StreamingGenerator

### ISSUE THREAD

**Issue by mohamedSulaimanAlmarzooqi** [synthizer/synthizer-rs#1]
Hello, I noticed that StreamingGenerator doesn't have set_looping, IS this a bugg or am I not ment to make this loop?

**Comment by ahicks92** [comment]
It's a bug. I just pushed a fix. I don't have time to babysit a release though so you'll need to get cargo depending on this GitHub repo for the time being.  I don't remember how offhand.

If there's a property in the main Synthizer manual and not in the Rust bindings that's an oversight.  There's lists that have to be maintained by hand and if they don't match up things are missing on this side.

**Comment by ahicks92** [comment]
Just pushed the release that has this in it.
