### ISSUE TITLE
Failed building Synthizer on Windows

### ISSUE THREAD

**Issue by StormyNight2020** [synthizer/synthizer-rs#5]
I am trying to build Synthizer version 0.4.5 on Windows 10 64 bit using rustc 1.58.1 (db9d1b20b 2022-01-20). I tried to build using MSVCShell with C++ workload installed. I am receiving the following:
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now',

Any feedback would be appreciated.

**Comment by ahicks92** [comment]
I really can't help without more than that.  Note that we have Windows CI passing.  Are you sure you have cmake?

**Comment by ahicks92** [comment]
I see you closed.  Did you solve it?
