### ISSUE TITLE
fix TryFrom conversions

### ISSUE THREAD

**Issue by ahicks92** [synthizer/synthizer-rs#6]
@ndarilek
We already had unit tests for some of this but master now also implements TryFrom for non-reference types. At the moment, though, I think your code snippet should have worked before the latest commit on master, so I'm not sure what's up.  Can you make sure you're up to date, and possibly point Cargo at master and see if the changes I just pushed fix this for you?

**Comment by ndarilek** [comment]
Sure thing, I won't be able to get to it this weekend but will try first 
thing Monday and get back to you. Thanks!

**Comment by ndarilek** [comment]
Works fine now. Thanks!

**Comment by ahicks92** [comment]
This is now live on crates.io.
